// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVvHFyj3k1ED7Bpxk_wMMI8XvGBJ4u28',
    appId: '1:862770880328:web:2434d7689189ccbb44dd7d',
    messagingSenderId: '862770880328',
    projectId: 'weatherapp-77732',
    authDomain: 'weatherapp-77732.firebaseapp.com',
    storageBucket: 'weatherapp-77732.appspot.com',
    measurementId: 'G-PVW4M6ELB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPshLvzgy4LpXaaHhLMZtbYUSd7X1oXm8',
    appId: '1:862770880328:android:fa620578e4c70f5844dd7d',
    messagingSenderId: '862770880328',
    projectId: 'weatherapp-77732',
    storageBucket: 'weatherapp-77732.appspot.com',
  );
}
